#文档块
server:
  port: 8081
---
server:
  port: 8083
spring:
  profiles: dev
    active: dev

---


#server:
#  port: 8081
#
#person:
#  lastName: zhang
#  age: 18
#  boss: false
#  birth: 2017/12/12
#
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhangsan
#    - bosheng
#  dog:
#    name: 小狗
#    age: 2